{
 "title": "Service of Ethereum staking monitoring",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "12s",
 "panels": [
  { "title": "Ethereum", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Стоимость ETH",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "max(eth_usd)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Капитализация стейкинга",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "$A*$B*32", "type": "math" }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 6, "x": 10, "y": 1 },
   "options": {
    "content": "<div style=\"width:100%;height:100%;display:flex;flex-direction:row;align-items:center;justify-content:center\">\n<img src=\"http://www.fa.ru/org/div/skp/Documents/logo.svg\" height=\"100%\" width=\"100%\" style=\"max-width:100%;max-height:100%;\"/>\n</div>"
   }
  },
  {
   "title": "Финализация эпохи",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 3, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "max(slot) % 32", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Активные валидаторы под мониторингом",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "max(own_validators_active)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Стоимость ETH в рублях",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "currencyRUB" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "max(eth_rub)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Эпоха",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 10, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "max(epoch)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Слот",
   "type": "stat",
   "description": "Ethereum слот",
   "gridPos": { "h": 3, "w": 3, "x": 13, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "max(slot)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Объём стейка под мониторингом",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "$A * $B * 32", "type": "math" }
   ]
  },
  {
   "title": "Активные валидаторы в сети",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "max(network_validators_active)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Валидаторы, ожидающие активации",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 4, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(network_validators_pending)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Доля, находящихся под мониторингом",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 9, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "100*$A/$B", "type": "math" }
   ]
  },
  {
   "title": "Доля отслеживаемых валидаторов в очереди",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "100*$A/$B", "type": "math" }
   ]
  },
  {
   "title": "Назначенные создания блоков",
   "type": "stat",
   "description": "В следующие 2 эпохи",
   "gridPos": { "h": 4, "w": 2, "x": 19, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "max(future_proposals)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Суточный процент полученных наград",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "$J/$I", "type": "math" }
   ]
  },
  {
   "title": "Время ожидания в очереди",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "max(activation_queue_gauge)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Доля блоков с Maximal Extracted Value",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 8, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "100*$A/$B", "type": "math" }
   ]
  },
  {
   "title": "Заслешенные валидаторы под мониторингом",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 13, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "max(own_validators_slashed)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Вышедшие отслеживаемые валидаторы",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 16, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "max(own_validators_exited)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Общее количество заслешенных валидаторов",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "max(network_validators_slahed)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Доля заработанных наград по сети (сутки)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "$J/$I", "type": "math" }
   ]
  },
  {
   "title": "Возможная суточная награда",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "ETH" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "($A+$B+$C)/10**9", "type": "math" }
   ]
  },
  {
   "title": "Возможная суточная эмиссия",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "ETH" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "($A+$B+$C)/10**9", "type": "math" }
   ]
  },
  {
   "title": "Действительная суточная эмиссия",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "ETH" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "($A-$B+$C-$D+$E)/10**9", "type": "math" }
   ]
  },
  {
   "title": "Потерянные награды и штрафы (сутки)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 16, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "ETH" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "($J-$I)/10**9", "type": "math" }
   ]
  },
  {
   "title": "Отслеживаемые валидаторы в очереди",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "max(own_validators_pending)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Полученная суточная награда",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "ETH" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "($A-$B+$C-$D+$E)/10**9", "type": "math" }
   ]
  },
  {
   "title": "Потерянная суточная эмиссия",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 16, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "ETH" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "($J-$I)/10**9", "type": "math" }
   ]
  },
  {
   "title": "Вознаграждение за производство блоков",
   "type": "stat",
   "description": "с момента старта сервиса",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "ETH" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "$A", "type": "math" }
   ]
  },
  {
   "title": "Уровень участия в консенсусе",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expr": "max(attestation_rate_gauge)", "legendFormat": "Вся эпоха" },
    {
     "expr": "max(min_over_time(attestation_rate_gauge[2m]))",
     "legendFormat": "В теч. 2 мин"
    }
   ]
  },
  {
   "title": "Source-аттестации (Source rate)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    { "expr": "max(network_source_rate)", "legendFormat": "Сеть" },
    { "expr": "max(own_source_rate)", "legendFormat": "Отслеживаемые валидаторы" }
   ]
  },
  {
   "title": "Target-аттестации (target rate)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    { "expr": "max(network_target_rate)", "legendFormat": "Сеть" },
    { "expr": "max(own_target_rate)", "legendFormat": "Отслеживаемые валидаторы" }
   ]
  },
  {
   "title": "Head-аттестации (head rate)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    { "expr": "max(network_head_rate)", "legendFormat": "Сеть" },
    { "expr": "max(own_head_rate)", "legendFormat": "Отслеживаемые валидаторы" }
   ]
  },
  {
   "title": "Пропущенные аттестации последнюю эпоху",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 38 },
   "targets": [
    { "expr": "max(n_missed_attestations)", "legendFormat": "Единичная" },
    {
     "expr": "max(n_paired_missed_attestations)",
     "legendFormat": "Две подряд"
    }
   ]
  },
  {
   "title": "Пропущенные блоки за последние сутки",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 45 },
   "targets": [
    {
     "expr": "max(increase(n_missed_head_proposals_total[24h]))",
     "legendFormat": "Не финализирован (head)"
    },
    {
     "expr": "max(increase(n_missed_finalized_proposals_total[24h]))",
     "legendFormat": "Финализирован"
    }
   ]
  },
  {
   "title": "Логирование",
   "type": "logs",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 52 },
   "targets": [
    {
     "expr": "{app=\"beamon\"}"
    }
   ]
  }
 ]
}